language: scala

matrix:
  include:
    - jdk: openjdk8
      scala: '2.13.1'
    - jdk: openjdk11
      scala: '2.13.1'
    - jdk: openjdk8
      scala: '2.11.12'
    - jdk: openjdk11
      scala: '2.11.12'
    - jdk: openjdk8
      scala: '2.12.10'
    - jdk: openjdk11
      scala: '2.12.10'

script:
  - sbt ++$TRAVIS_SCALA_VERSION ci

env:
  global:
    - COURSIER_PROGRESS=0

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
