language: scala

matrix:
  include:
    - jdk: oraclejdk8
      scala: '2.13.0'
      script:
      - sbt "++${TRAVIS_SCALA_VERSION}!" coreJVM/test coreJS/test scratch/test # TODO cats-effect for Scala 2.13
    - jdk: oraclejdk11
      scala: '2.13.0'
      script:
      - sbt "++${TRAVIS_SCALA_VERSION}!" coreJVM/test coreJS/test scratch/test # TODO cats-effect for Scala 2.13
    - jdk: oraclejdk8
      scala: '2.11.12'
    - jdk: oraclejdk11
      scala: '2.11.12'
    - jdk: oraclejdk8
      scala: '2.12.8'
    - jdk: oraclejdk11
      scala: '2.12.8'

script:
  - sbt ++$TRAVIS_SCALA_VERSION ci

env:
  global:
    - COURSIER_PROGRESS=0

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
